# Generated by Django 3.2.7 on 2021-09-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
